on: [pull_request]

jobs:
  simple:
    runs-on: docker
    container:
      image: code.forgejo.org/oci/debian:bookworm

    services:
      pgsql:
        image: code.forgejo.org/oci/postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
    steps:
      - run: |
          set -x
          cat /etc/hosts
          getent hosts pgsql
          apt-get update -qq
          apt-get install -y -qq  postgresql-client
          PGPASSWORD=postgres psql -h pgsql -U postgres -c '\dt' test
          sleep 30000

