apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buildkit-ca
spec:
  isCA: true
  commonName: buildkit-ca
  secretName: buildkit-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: Issuer
    name: buildkit-self-signed
