// Copyright 2025 The Forgejo Authors. All rights reserved.
// Copyright 2023 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package config

import (
	"bytes"
	"encoding/json"
	"os"

	"github.com/google/go-cmp/cmp"
)

const RegistrationWarning = "This file is automatically generated by forgejo-runner. Do not edit it manually unless you know what you are doing. Removing this file will cause act runner to re-register as a new runner."

// Registration is the registration information for a runner
type Registration struct {
	Warning string `json:"WARNING"` // Warning message to display, it's always the RegistrationWarning constant

	ID      int64    `json:"id"`
	UUID    string   `json:"uuid"`
	Name    string   `json:"name"`
	Token   string   `json:"token"`
	Address string   `json:"address"`
	Labels  []string `json:"labels"`
}

func LoadRegistration(file string) (*Registration, error) {
	regs, err := LoadRegistrations(file)
	if err != nil {
		return nil, err
	}
	if len(regs) == 0 {
		return nil, os.ErrInvalid
	}
	return regs[0], nil
}

func LoadRegistrations(file string) ([]*Registration, error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}

	data = bytes.TrimSpace(data)
	if len(data) == 0 {
		return nil, os.ErrInvalid
	}

	if data[0] == '[' {
		var regs []*Registration
		if err := json.Unmarshal(data, &regs); err != nil {
			return nil, err
		}
		return regs, nil
	}

	var reg Registration
	if err := json.Unmarshal(data, &reg); err != nil {
		return nil, err
	}
	return []*Registration{&reg}, nil
}

func isEqualRegistration(file string, reg *Registration) (bool, error) {
	regs, err := LoadRegistrations(file)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	for _, r := range regs {
		// Prefer UUID matching when both have UUIDs
		if r.UUID != "" && reg.UUID != "" {
			if r.UUID == reg.UUID {
				return cmp.Equal(*reg, *r), nil
			}
			continue
		}
		// Only fall back to address matching if at least one lacks UUID
		if r.Address == reg.Address {
			return cmp.Equal(*reg, *r), nil
		}
	}
	return false, nil
}

func SaveRegistration(file string, reg *Registration) error {
	regs, err := LoadRegistrations(file)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		regs = []*Registration{}
	}

	found := false
	for i, r := range regs {
		matched := false
		// Prefer UUID matching when both have UUIDs
		if r.UUID != "" && reg.UUID != "" {
			if r.UUID == reg.UUID {
				matched = true
			}
		} else if r.Address == reg.Address {
			// Only fall back to address matching if at least one lacks UUID
			matched = true
		}

		if matched {
			if cmp.Equal(*r, *reg) {
				return nil
			}
			regs[i] = reg
			found = true
			break
		}
	}

	if !found {
		regs = append(regs, reg)
	}

	return SaveRegistrations(file, regs)
}

func SaveRegistrations(file string, regs []*Registration) error {
	for _, reg := range regs {
		reg.Warning = RegistrationWarning
	}

	f, err := os.Create(file)
	if err != nil {
		return err
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")

	// If there is only one registration, we save it as a single object
	// for backward compatibility with older versions of the runner.
	// Note: This means that if a user manually changes the file to an array
	// containing a single registration, it will be rewritten as a single object.
	if len(regs) == 1 {
		return enc.Encode(regs[0])
	}
	return enc.Encode(regs)
}
