name: build

on:
  push:
    paths:
      - .forgejo/workflows/build.yaml
      - airflow/Dockerfile       # Trigger only if Dockerfile is changed
      - airflow/requirements.txt # Trigger only if requirements.txt is changed

env:
  REGISTRY: ${{ github.server_url }}
  APP: airflow
  CONTEXT: airflow
  DOCKERFILE: Dockerfile

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v6

      - name: Compute image tag
        id: vars
        run: |
          REGISTRY="${GITHUB_SERVER_URL#*//}"
          REPOSITORY="${GITHUB_REPOSITORY}"
          # Extract version from Dockerfile using sed (BusyBox compatible)
          KC_VERSION=$(sed -n '/^FROM/ s/.*:\([^ ]*\).*/\1/p' "${CONTEXT}/${DOCKERFILE}")
          TAG="${KC_VERSION}-${GITHUB_SHA::8}"

          echo "registry=${REGISTRY}"          >> $GITHUB_OUTPUT
          echo "repository=${REPOSITORY}"      >> $GITHUB_OUTPUT
          echo "tag=${TAG}"                    >> $GITHUB_OUTPUT
          echo "full_image=${REGISTRY}/${REPOSITORY}/${APP}:${TAG}" >> $GITHUB_OUTPUT

      - name: Docker CLI installation
        run: |
          apt update
          apt install -y ca-certificates curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Login to Container Registry
        run: |
          echo "${{ secrets.PASSWORD_WRITE_REPOSITORY }}" | \
          docker login ${{ steps.vars.outputs.registry }} \
            -u ${{ secrets.USERNAME_WRITE_REPOSITORY }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -f ${{ env.CONTEXT }}/${{ env.DOCKERFILE }} \
            -t ${{ steps.vars.outputs.full_image }} \
            ${{ env.CONTEXT }}

      - name: Push image
        run: docker push ${{ steps.vars.outputs.full_image }}

      - name: Summary
        run: |
          echo "### ✅ Image pushed: ${{ steps.vars.outputs.full_image }}" >> $GITHUB_STEP_SUMMARY
